from __future__ import annotations

from pathlib import Path

from .toolchains import DetectionResult, detect_toolchains
from .workspace import ensure_hidden_workspace

FORGE_GATES_MANAGED_MARKER = "AUTO-GENERATED BY FORGE"


class ManualGateOwnershipError(RuntimeError):
    pass


def display_gate_path(gates_file: Path, repo_root: Path) -> str:
    try:
        return gates_file.relative_to(repo_root).as_posix()
    except ValueError:
        return str(gates_file)


def render_quality_gates(
    result: DetectionResult,
    gates_file: Path,
    repo_root: Path,
) -> str:
    gate_label = display_gate_path(gates_file, repo_root)
    lines = [
        "#!/usr/bin/env bash",
        f"# {gate_label} — {FORGE_GATES_MANAGED_MARKER}",
        "# Generated by forge.sh after inspecting the current target repo.",
        "# Delete the managed marker line if you need to take permanent manual ownership.",
        "",
        "set -euo pipefail",
        "",
        'echo "[GATES] Forge-managed gate file"',
    ]

    if result.toolchains:
        joined = ", ".join(result.toolchains)
        lines.append(f'echo "[GATES] Detected toolchains: {joined}"')
    notes = result.notes if result.notes else ("",)
    for note in notes:
        lines.append(f'echo "[GATES] Note: {note}"')
    lines.append("")

    if not result.gate_commands:
        lines.extend(
            [
                'echo "[GATES] Running safe structural fallback checks..."',
                'test -f "${FORGE_PRD_FILE:-prd.json}"',
                "git rev-parse --is-inside-work-tree >/dev/null",
                'echo "[GATES] Fallback checks passed."',
            ]
        )
    else:
        for command in result.gate_commands:
            lines.append(f'echo "[GATES] Running: {command}"')
            lines.append(command)
            lines.append("")
        lines.append('echo "[GATES] All auto-generated gates passed."')

    lines.append("exit 0")
    lines.append("")
    return "\n".join(lines)


def is_manual_gate_file(path: Path) -> bool:
    if not path.exists():
        return False
    return FORGE_GATES_MANAGED_MARKER not in path.read_text(encoding="utf-8")


def write_quality_gates(gates_file: Path, contents: str) -> None:
    gates_file.parent.mkdir(parents=True, exist_ok=True)
    gates_file.write_text(contents, encoding="utf-8")
    gates_file.chmod(gates_file.stat().st_mode | 0o111)


def generate_gates(
    repo_root: Path,
    workspace_dir: Path,
    source_root: Path,
    gates_file: Path | None = None,
) -> tuple[Path, DetectionResult]:
    resolved_gates_file = gates_file or workspace_dir / "forge.gates.sh"
    ensure_hidden_workspace(
        repo_root=repo_root,
        workspace_dir=workspace_dir,
        source_root=source_root,
        gates_file=resolved_gates_file,
    )

    if is_manual_gate_file(resolved_gates_file):
        raise ManualGateOwnershipError(
            f"Preserving manual gate file at {resolved_gates_file}. "
            "Remove manual ownership to re-enable auto-generation."
        )

    result = detect_toolchains(repo_root)
    rendered = render_quality_gates(result, resolved_gates_file, repo_root)
    write_quality_gates(resolved_gates_file, rendered)
    return resolved_gates_file, result
